version: 0.2
env:
  runtime-versions:
    nodejs: latest
phases:
  pre_build:
    commands:
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  files:
    - "**/*"
  base-directory: build
cache:
  paths:
    - ~/.cache
    - ~/.npm
